### ISSUE TITLE
Linux page in side bar

### ISSUE THREAD

**Issue by Simplenuity** [abstractspoon/ToDoList_Wiki#14]
Hi Tony,

If you're fine with it I would create a subtitle under Installation for [https://github.com/abstractspoon/ToDoList_Wiki/wiki/Linux](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Linux).

Also, I assume you're still in the process of ordering the sidebar, aren't you? For example, I would list the Installation page before discussing Task Fields.

Ryan

**Comment by TonyGravagno** [comment]
Thanks @Simplenuity. I've updated the Installation page with a link to your Linux page as well as a request for info about OSX from anyone who uses it with TDL.

I've also updated the sidebar - good suggestions, thanks. My thought on that sidebar has been that I want to provide material up-front for people to become familiar with the software before getting into the details of installing it. In this case, you're right, the list of detailed fields is irrelevant until it's installed. However the introduction to fields is now below the installation. What do you think?

Related, the I have the link for "Reporting Bugs And Enhancements (Issues)" directly under Getting Help, because those topics are related. I feel it's important to have Getting Help above the Installation to prep folks and let them know support is available. But Issues can only really be reported after the install.

Point is - that I'm trying to balance some of these factors here but it's easy for me to get it wrong. And in that little sidebar we also want to balance a limited amount of real-estate with an increasing wealth of categorized information. So if you or anyone else has logical suggestions for how it can be organized better, I'm all ears. :ear: ... And I expect it will evolve over time.

Thanks.

**Comment by Simplenuity** [comment]
Hi Tony,

Thanks for adding the Linux page to the sidebar!

Absolutely agree with your thoughts on that sidebar:
- general info about TDL on top
- getting Help, including reporting bugs, next, so that everyone stumbles on it
- the actual manual below

Sure it will evolve (and change) as the time goes by. I definitely will also keep an eye on it and will let you know if I get any ideas for improvements.

What I already figured out is that we need to make sure to distribute this URL to end users:
[https://github.com/abstractspoon/ToDoList_Wiki/wiki](https://github.com/abstractspoon/ToDoList_Wiki/wiki)
instead of this one:
[https://github.com/abstractspoon/ToDoList_Wiki](https://github.com/abstractspoon/ToDoList_Wiki)

Ryan

**Comment by TonyGravagno** [comment]
> What I already figured out is that we need to make sure to distribute this URL to end users:
> https://github.com/abstractspoon/ToDoList_Wiki/wiki
> instead of this one:
> https://github.com/abstractspoon/ToDoList_Wiki

You're right that the recommended link goes to the wiki itself, which is where we really want people to go. The second link brings people to the repo which provides info about the wiki itself. Either one is valid but the /wiki link is better for this purpose. Similarly the /issues link is better for _Issues. I'll keep this in mind when posting links. Thanks.
