### ISSUE TITLE
Markdown and MultiMarkdown in Wiki?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#19]
I tried some formatting with Markdown and Multimarkdown (eg. "tables"). The link above this edit box writes only "Markdown supported", but "Multimarkdown" seems to be (partially??) supported ...

What's the real situation?

**Comment by TonyGravagno** [comment]
GitHub uses a subset of the [Gollum](https://github.com/gollum/gollum) wiki. The subset is called [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) or GFM. Your confusion is understood. I've had to spend a lot of time reading forums, blogs, and wikis, and I've had to do a lot of experimenting to get specific things to work.

Please always use the default Markdown for pages. For example, don't change the dropdown selection so that we have some RDoc pages and some Markdown.

I think the best way to figure out how to do things is to learn by example. Find pages that have the structures you want and then click Edit to see the source. I created a repo of my own to experiment in a sandbox. That's good for learning too.

There is sometimes more than one way to do things. For tables as an example, I used the markdown code to create a table [here](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Fields). (Ugh, what a hassle) Then I realized I could use a regular HTML table on [this](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Command-Line) page. I'm going to re-work the markdown version to HTML now that I know we can do that.

For link anchors we need a div tag where I've used both the ID and the NAME attributes just in case there are browser-specific issues. (I had to do some reading on that too.) See the [Command-Line](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Command-Line) page again for lots of local page links.

Rather than creating a wiki "Issue" with a question, please use one of the forums. The Google forum might be best for this since it's not TDL-specific, and then the Q&A will be entirely in the public.

However, let's finish this conversation and you can close this item when your questions are answered.

HTH

**Comment by Pierre-de-la-Verre** [comment]
Thanks, Tony. Closed
