### ISSUE TITLE
Marking the link text in a task with keys STRG + A marks all tasks too

### ISSUE THREAD

**Issue by Schack17** [abstractspoon/ToDoList_Wiki#36]
1. I click in the Link field of a task.
2. I press STRG + A to mark the text of the link.
3. Now the text of the link is marked but all tasks too.
4. With STRG + C all tasks are copied in the clipboard not the text of the task link!

Please re enable the mark function of the task link.
In Version 6.x it worked fine.

**Comment by Schack17** [comment]
Oh: Fixed since 7.0.6. - Thanks!

**Comment by Pierre-de-la-Verre** [comment]
Hi Schack17

i will close this issue, because you wrote that it is fixed in 7.0.6. If the issue still occurs, please post to Google groups:

Visit this group at http://groups.google.com/group/abstractspoon-todolist-support.
To view this discussion on the web, visit https://groups.google.com/d/msgid/abstractspoon-todolist-support/97ae005e-2d85-40f9-a8b6-a75cf67600c1%40googlegroups.com.

**Comment by Schack17** [comment]
Hello Pierre,

I had this problem in 7.0.6. Today with 7.0.7 it is fixed. 
Thanks.
