### ISSUE TITLE
Highlight mismatch and inability to change order of tasks with subtasks

### ISSUE THREAD

**Issue by PatrickRyder** [abstractspoon/ToDoList_Wiki#37]
Hi,

I have encountered a couple of problems using To Do List 7.0.

The first problem was discovering I could not change the order of 'folders' (i.e. tasks that have subtasks).  Whether I use the mouse or the keyboard, the order of the folders will not change.  Tasks that do not have subtasks can still be reordered using keyboard or mouse.  Note, I have the sorting set to None.

While investigating the above issue, I then noticed the highlight on the status columns was one line out from the highlight on the task title.  Screenshot attached.
![capture](https://cloud.githubusercontent.com/assets/13526323/10935300/1b653ae4-82dd-11e5-8d1c-e10ba3641256.PNG)

Kind wishes ~ Patrick

**Comment by Pierre-de-la-Verre** [comment]
Hi Patrick
this is not the best place to discuss an issue. Please use the forum at Codeproject or at GoogleGroups:

http://www.codeproject.com/Articles/5371/ToDoList-An-effective-and-flexible-way-to-keep-on
https://groups.google.com/forum/#!forum/abstractspoon-todolist-support
https://groups.google.com/forum/#!msg/abstractspoon-todolist-support/F8NCjqHhIsA/N9Ygy3KFAQAJ

Please close this issue here.

**Comment by Pierre-de-la-Verre** [comment]
BTW: Do you still use version 7.0? If so, you should update to current version 7.0.7 - e.g. the "highlight" issue (and maybe the "sorting" too) are already fixed.

**Comment by PatrickRyder** [comment]
Thanks for the correction.

I did find the newer version after posting the bug, and it has perhaps solved the problem.  I can't say for certain yet because I was using 7.0 for about three weeks before the bug popped up.  If it reoccurs, I will repost in the proper place.
